version: '3.3'

services:
  react-frontend:
    container_name: lineupx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development